Update packege and integration tests step in main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,3 +33,48 @@ jobs:
       - name: Docker cleanup
         if: always()
         run: docker compose down -v
+        
+  packeage-and-integration-tests:
+    name: Packege & Integration Tests
+    runs-on: ubuntu-latest
+    needs: build-and-test
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Build and tag Docker image
+        run: |
+          docker build -t task-manager:${{ env.IMAGE_TAG }} .
+          docker tag task-manager :${{ env.IMAGE_TAG }} task-manager:latest
+
+      - name: Save Docker image artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: docker-image
+          path: task-manager-image.tar.gz
+          retention-days: 1
+
+      - name: Start E2E environment
+        run: docker compose up -d
+
+      - name: Run Integration Tests
+        run: |
+          for i in {1..20}; do
+            if curl -s http://localhost:5000 > /dev/null; then
+              echo "App is up!"
+              exit 0
+            fi
+            echo "Waiting for app..."
+            sleep 1
+          done
+
+          echo "App failed to start"
+          exit 1
+      
+      - name: Stop E2E environment
+        run: docker compose down
+          
+          
+      
+      
